apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: micro-service
build:
  artifacts:
  - image: order
    context: order
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: payment
    context: payment
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: shipping
    context: shipping
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - order/deployment.yaml
    - payment/deployment.yaml
    - shipping/deployment.yaml
